# Generated by Django 3.2.5 on 2021-08-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
                ('Skills', models.CharField(max_length=50)),
                ('Qaulification', models.CharField(max_length=50)),
                ('Experience', models.CharField(max_length=50)),
                ('DOB', models.DateField(default='2021-01-05')),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('profile_Pic', models.ImageField(default='abc.jpg', upload_to='img/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
